#!/usr/bin/env python3
"""
simple_circuit

Generated from: unknown
Generated by: kicad-sch-api v0.5.0
Date: 2025-11-07T00:48:53.712472
"""

import kicad_sch_api as ksa


def create_simple_circuit():
    """Create simple_circuit schematic."""

    # Create schematic
    sch = ksa.create_schematic('simple_circuit')

    # Add components
    r1 = sch.components.add(
        'Device:R',
        reference='R1',
        value='10k',
        position=(96.52, 100.33)
    )
    # Add wires
    sch.add_wire(
        start=(96.52, 96.52),
        end=(93.98, 96.52)
    )
    sch.add_wire(
        start=(93.98, 104.14),
        end=(96.52, 104.14)
    )
    sch.add_wire(
        start=(93.98, 96.52),
        end=(93.98, 104.14)
    )

    return sch


if __name__ == '__main__':
    schematic = create_simple_circuit()
    schematic.save('simple_circuit.kicad_sch')
    print('✅ Schematic generated: simple_circuit.kicad_sch')